"PR: Docs":
- changed-files:
  - any-glob-to-all-files: ['docs/*', 'guides/*', '**/*.md']

"PR: Chore":
- changed-files:
  - any-glob-to-all-files: ['.github/*', '**/*.yml', '.gitattributes', '.gitignore']

"PR: JSON":
- changed-files:
  - all-globs-to-all-files: ['**/*.json']

"PR: Audio":
- changed-files:
  - any-glob-to-any-files: ['**/snd_*', '**/*.ogg', '**/*.wav']

"PR: Sprites":
- changed-files:
  - any-glob-to-any-files: ['**/*.png', '**/spr_*']
  
