"Type: Docs":
- changed-files:
  - any-glob-to-any-file: ['docs/*', 'guides/*', '**/*.md']

"Type: CI":
- changed-files:
  - any-glob-to-any-file: ['.github/*', '**/*.yml', '.gitattributes', '.gitignore']

"Area: JSON":
- changed-files:
  - all-globs-to-any-file: ['**/*.json']

"Area: Audio":
- changed-files:
  - any-glob-to-any-file: ['**/snd_*', '**/*.ogg', '**/*.wav']

"Area: Sprites":
- changed-files:
  - any-glob-to-any-file: ['**/*.png', '**/spr_*']
  
