changelog:
  categories:
    - title: Possibly Breaking Changes
      labels:
        - "Breaking!"
        
    - title: New/Changed
      labels:
        - "Type: Feature"
        - "Enhancement"
        - "Balance"
        - "Misc Change"
        
    - title: Fixes
      labels:
        - "Type: Fix"
        
    - title: Under The Hood - Big!
      labels:
        - "Size: Warning"
        - "Size: Epic"
        - "Size: Huge"
        
    - title: Under The Hood
      labels:
        - "Type: Refactor"
        - "Type: Performance"
        - "Type: Code Style"
        - "Type: Docs"
        - "Type: CI"
        
    - title: Other Changes
      labels:
        - "*"
