# .github/release.yml

changelog:
  exclude:
    labels:
      - PR: Docs
  categories:
    - title: Possibly Breaking Changes:
      labels:
        - PR: Breaking!
        - PR: Major Feat!
    - title: New/Changed:
      labels:
        - PR: Feature
        - PR: Misc Change
    - title: Fixes:
      labels:
        - PR: Fix
        - PR: Performance
    - title: Other Changes:
      labels:
        - "*"
