version: 1
appendOnly: true
labels:
- label: "PR: Breaking!"
  title: "!"
- label: "PR: Breaking!"
  body: "\[breaking\]"

- label: "PR: Chore"
  title: "^chore"
- label: "PR: Chore"
  body: "\[chore\]"

- label: "PR: Docs"
  title: "^docs"
- label: "PR: Docs"
  body: "(\[docs\]|\[doc\])"

- label: "PR: Code Style"
  title: "^style"
- label: "PR: Code Style"
  body: "\[style\]"

- label: "PR: Feature"
  title: "^feat"
- label: "PR: Feature"
  body: "(\[feature\]|\[feat\])"

- label: "PR: Fix"
  title: "^fix"
- label: "PR: Fix"
  body: "\[fix\]"

- label: "PR: Refactor"
  title: "^refactor"
- label: "PR: Refactor"
  body: "(\[refactor\]|\[ref\])"

- label: "PR: Performance"
  title: "^perf"
- label: "PR: Performance"
  body: "(\[performance\]|\[perf\])"

- label: "PR: Major Coding"
  size:
    above: 800
