version: 1
appendOnly: true
labels:
- label: "PR: Breaking\\!"
  title: "\\!"
- label: "PR: Breaking\\!"
  body: "(?i)\\[breaking\\]"

- label: "PR: Chore"
  title: "^chore"
- label: "PR: Chore"
  body: "(?i)\\[chore\\]"

- label: "PR: Docs"
  title: "^docs"
- label: "PR: Docs"
  body: "(?i)(\\[docs\\]|\\[doc\\])"

- label: "PR: Code Style"
  title: "^style"
- label: "PR: Code Style"
  body: "(?i)\\[style\\]"

- label: "PR: Feature"
  title: "^feat"
- label: "PR: Feature"
  body: "(?i)(\\[feature\\]|\\[feat\\])"

- label: "PR: Fix"
  title: "^fix"
- label: "PR: Fix"
  body: "(?i)\\[fix\\]"

- label: "PR: Refactor"
  title: "^refactor"
- label: "PR: Refactor"
  body: "(?i)(\\[refactor\\]|\\[ref\\])"

- label: "PR: Performance"
  title: "^perf"
- label: "PR: Performance"
  body: "(?i)(\\[performance\\]|\\[perf\\])"

- label: "Size: Tiny"
  size:
    below: 50

- label: "Size: Small"
  size:
    above: 49
    below: 200

- label: "Size: Medium"
  size:
    above: 199
    below: 400

- label: "Size: Big"
  size:
    above: 399
    below: 800

- label: "Size: Huge"
  size:
    above: 799
    below: 1600

- label: "Size: Epic"
  size:
    above: 1599
