name: Discord Release Notification
on:
  release:
    types: [prereleased, published]
permissions:
    contents: read
jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GitHub Releases to Discord
        uses: SethCohen/github-releases-to-discord@v1.19.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: "GitHub Releases"
          content: "@Development Builds"
          reduce_headings: true
