name: Discord Release Notification
on:
  release:
    types: [prereleased]
permissions:
    contents: read
jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug GitHub Event
        run: |
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "GitHub Event Action: ${{ github.event.action }}"
          echo "Release ID: ${{ github.event.release.id }}"
          echo "Release Tag Name: ${{ github.event.release.tag_name }}"
          echo "Release Prerelease: ${{ github.event.release.prerelease }}"
          echo "Release Draft: ${{ github.event.release.draft }}"

      - name: GitHub Releases to Discord
        uses: SethCohen/github-releases-to-discord@v1.19.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: "GitHub Releases"
          content: "<@&1318332223232938014>"
          reduce_headings: true
