name: Release-Development
on: 
  workflow_dispatch:
    inputs:
      compiler:
        type: choice
        description: What compiler to use?
        required: true
        default: YYC
        options: 
          - YYC
          - VM
  schedule:
    - cron: "0 0 * * *"

env:
  MAIN_TAG: nightly
  PREV_TAG: nightly-prev

jobs:
  release_type:
    name: Release Type
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Tag Names
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "MAIN_TAG=nightly" >> $GITHUB_ENV
            echo "PREV_TAG=nightly-prev" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/stable-candidate" ]; then
            echo "MAIN_TAG=stable-preview" >> $GITHUB_ENV
            echo "PREV_TAG=stable-preview-prev" >> $GITHUB_ENV
          else
            BRANCH_NAME=$(echo "${{ github.ref }}" | cut -d'/' -f3)
            BRANCH_NAME=${BRANCH_NAME##*/}
            echo "MAIN_TAG=${BRANCH_NAME}_preview" >> $GITHUB_ENV
            echo "PREV_TAG=${BRANCH_NAME}_preview-prev" >> $GITHUB_ENV
          fi

  build_needed:
    name: Build needed?
    runs-on: ubuntu-latest
    outputs:
      needs_build: ${{ steps.commit_check.outputs.needs_build }}  # Output for skipping
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Check commit
        id: commit_check
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Merge commit message: $COMMIT_MESSAGE"
          
          EXCLUDE_PATTERN="^(docs|chore|style|ci)"
          
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manually triggered, forcing build."
            echo "needs_build=true" >> $GITHUB_OUTPUT
          elif echo "$COMMIT_MESSAGE" | grep -Eq "$EXCLUDE_PATTERN"; then
            echo "Commit message matches excluded pattern, skipping build."
            echo "needs_build=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Workflow triggered by a scheduled run. Continuing..."
            echo "needs_build=false" >> $GITHUB_OUTPUT;
          fi

      - name: Checkout code
        if: ${{ steps.commit_check.outputs.needs_build == 'false' }}
        uses: actions/checkout@v4

      - name: Fetch tags
        if: ${{ steps.commit_check.outputs.needs_build == 'false' }}
        run: git fetch --tags origin

      - name: Check if tags point to the same commit
        if: ${{ steps.commit_check.outputs.needs_build == 'false' }}
        id: check_tags
        run: |
          curr_sha=$(git rev-parse HEAD)
          prev_sha=$(git rev-parse ${{ env.PREV_TAG }} 2>/dev/null)

          if [[ $? -ne 0 ]]; then
            echo "Tag ${{ env.PREV_TAG }} cannot be resolved. Continuing..."
            echo "needs_build=true" >> $GITHUB_OUTPUT;
          elif [[ "$curr_sha" == "$prev_sha" ]]; then
            echo "No changes since last nightly release. Exiting..."
            echo "needs_build=false" >> $GITHUB_OUTPUT;
          else
            echo "Changes since last nightly release detected. Continuing..."
            echo "needs_build=true" >> $GITHUB_OUTPUT;
          fi

  gamemaker_build:
    name: Build
    uses: ./.github/workflows/gamemaker_build.yml
    secrets: inherit
    needs: build_needed
    if: needs.build_needed.outputs.needs_build == 'true'
    with:
      yyc: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.compiler == 'YYC' || github.event_name != 'workflow_dispatch' }}

  release:
    name: Release
    runs-on: windows-2022
    needs: gamemaker_build
    if: needs.build_needed.outputs.needs_build == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Check if a dev release exists
        id: check_release
        run: |
          gh release view ${{ env.MAIN_TAG }} --repo ${{ github.repository }}
          if [ $? -eq 0 ] ; then
            echo "release_exists=true" >> $GITHUB_OUTPUT;
          else
            echo "release_exists=false" >> $GITHUB_OUTPUT;
          fi
        shell: bash
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: get_commit_sha
        name: Get commit SHA of the last nightly release
        if: steps.check_release.outputs.release_exists
        run: |
          $prev_sha = git rev-parse ${{ env.MAIN_TAG }}
          echo "prev_SHA=$prev_sha" >> $env:GITHUB_ENV

      - name: Update tag pointing to the previous nightly release
        if: steps.check_release.outputs.release_exists
        run: |
          # Get the SHA from the environment variable
          $sha = $env:prev_SHA
          # Construct the URL properly
          $url = "https://api.github.com/repos/$env:GITHUB_REPOSITORY/git/refs/tags/$env:PREV_TAG"
      
          # Create the JSON payload for the PATCH request
          $data = @{
            sha = $sha
          } | ConvertTo-Json
      
          # Use curl to send the PATCH request with proper headers and data
          curl --fail-with-body -X PATCH `
            -H "Authorization: Bearer ${{ secrets.WORKFLOW_TOKEN }}" `
            -H "Accept: application/vnd.github.v3+json" `
            -d $data `
            $url

      - id: delete_release_tag
        name: Delete the existing dev tag and release
        if: steps.check_release.outputs.release_exists
        run: |
          gh release delete ${{ env.MAIN_TAG }} -y --cleanup-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download built file artifact
        uses: actions/download-artifact@v4
        with:
          name: built-file
          path: ./build_output

      - id: create_release
        name: Create a release and upload the build
        uses: softprops/action-gh-release@v2.0.9
        with:
          name: ChapterMaster ${{ needs.gamemaker_build.outputs.suffix }}
          tag_name: ${{ env.MAIN_TAG }}
          prerelease: true
          generate_release_notes: true
          make_latest: true
          target_commitish: ${{ github.ref_name }}
          files: |
            ./build_output/${{ needs.gamemaker_build.outputs.built_file }}/*
