name: Release-Stable
on: 
  push:
    tags:        
      - v*.*.*
jobs:
  gamemaker_build:
    name: Build
    uses: ./.github/workflows/gamemaker_build.yml
    secrets: inherit
    with:
      yyc: true
      build_date: ""
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: gamemaker_build
    permissions:
      contents: write
    steps:
      - id: download_artifact
        name: Download built file artifact
        uses: actions/download-artifact@v4
        with:
          name: built-file
          path: ./build_output

      - id: create_release
        name: Create a release and upload the build
        uses: softprops/action-gh-release@v2.3.2
        with:
          name: ChapterMaster ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.RELEASE_TOKEN_SECRET }}
          prerelease: false
          generate_release_notes: true
          make_latest: true
          files: |
            ./build_output/${{ needs.gamemaker_build.outputs.built_file }}/*
