name: "Mark stale issues and PRs"
on:
  schedule:
    - cron: '0 22 * * *'  # every day at 22:00 UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-message: "This PR is marked as stale, because it has been open for 7 days with no activity."
          days-before-stale: 7
          days-before-issue-stale: -1
          days-before-close: -1
          stale-pr-label: "Status: Stale"
